### ISSUE TITLE
Truncated sequences in FASTQ output

### ISSUE THREAD

**Issue by OliverDeusch** [esrice/trio_binning#1]
I ran into an issue with classify_by_kmers using the precompiled binaries from version 0.2.3. Some sequences in the FASTQ files seem to be truncated. The header of the next sequence is printed directly after the sequence of the previous sequence and the quality information is missing completely.

Below is an example:

ATCTTTACTATTTTTCTCATTCATTTAAATAAAAAAAACACACTAATAAAATAATTATAATTTAATTCTTAAATTTTAATATTAAAATTTAATATTAAAAAAAAAAAAATACAAATAAAAATATATAAAAAAAATATTAAT     22 AACATCATATATAAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACATAAAAAATAAAATATAAAAATTAAATAATAAATTTAAATACACACAAAAAATATATAAAAAAAAAAAAAATAAAAAAATTTAAATAAAAA     22 AAAAAAAAAAAAAAATATTTAAATCTAATATTAAATAAAAAATAAATAAAAAAAAAAAAAAAAAATAAAAAAGACACTATCATAAAATATAAAAAAAAT@m64079_200214_171124/9/6976_13567
     23 ATTTTCAGGTTTATTTTCAAGCTAGGAACTTTTTCTACGATAAGTAAACTGTTTTTCCAGTGAAATCACTTCCCCCCGGAAGGGCTGAATTGGATCAAATTTCGACGAACATAAATACCCATTCATCACTCTAAACCACAG

I checked the BAM file and it is fine. I am now using the binning functionality in Canu directly.

**Comment by esrice** [comment]
Thanks for the bug report. Canu's binning functionality is probably the way to go now, so I recommend continuing this way. That being said, I'm working on fixing this now. It looks like an issue with compression libraries, so I'm going to try updating them and rebuilding the binaries. Were you outputting fastq.gz?

**Comment by esrice** [comment]
It is indeed an issue with the compression. Sadly, updating the compression library dependency did not solve it. There may be a maximum buffer size issue that is causing the truncation, since I'm currently writing full sequences to output all at once. I have made a new release with the compressed output option disabled for now, and hope to have more time to look into this later. Sorry I wasn't able to fully fix it at this time; you'll have to compress the output fastqs afterwards for now.
