### ISSUE TITLE
unclassified.fq

### ISSUE THREAD

**Issue by pengyan19** [esrice/trio_binning#12]
Hi, when i used the classify_by_kmers to cliassify the fastq file, we only assembly the paternal.fq and maternal.fq file. Did we discard the unclassified.fq?

**Comment by esrice** [comment]
Hi, it depends on how many of the reads end up in the unclassified bin. If the two haplotypes are very similar (i.e., the F1 has low heterozygosity), there might be a lot of reads that cannot be classified because they come from a part of the genome that is identical or near-identical between the two haplotypes, so the unclassified reads should be used in both the maternal and paternal assemblies. On the other hand, if the two haplotypes are very different, most every read should be classifyable into one of the two parental bins, so the unclassified bin will have mostly junk that can safely be disregarded (e.g., very short or inaccurate reads, contamination, etc.).

Hope this helps!
